repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-ast
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.5.2
    hooks:
    - id: isort
      args: ['--multi-line=3', '--trailing-comma', '--force-grid-wrap=0', '--use-parentheses', '--line-width=100']


-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports']

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.7
      args: ['--line-length=100']
