name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: alem_db
          POSTGRES_HOST: localhost
          POSTGRES_USER: alem_test
          POSTGRES_PASSWORD: password

        ports:
        - 5680:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install
      run: |
        pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run Tests
      run: |
        pytest
